services:
  golang:
    build:
      context: api
      dockerfile: ../docker/golang/Dockerfile
      target: dev
    volumes:
      - ./api/:/root
    ports:
      - "5000:5000"
    env_file: api/.env
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      context: docker/postgres
    env_file: api/.env
    volumes:
      - ./docker/init_db:/docker-entrypoint-initdb.d/schema
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  react:
    tty: true
    build:
      context: docker/react
      target: dev
    volumes:
      - ./react:/root
    ports:
      - "3050:3000"

  nginx:
    build:
      context: docker/nginx
      target: dev
    ports:
      - "80:80"
    depends_on:
      - react
      - golang
