services:
  golang:
    build:
      context: api
      dockerfile: ../docker/golang/Dockerfile
      target: dev
    volumes:
      - ./api/:/root
    ports:
      - ${API_PORT}:5000
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      context: docker/postgres
    env_file:
      - .env
    volumes:
      - ./docker/init_db:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  react:
    tty: true
    build:
      context: docker/react
      target: dev
    volumes:
      - ./react:/root
    ports:
      - ${REACT_PORT}:3000

  nginx:
    build:
      context: docker/nginx
      target: dev
    ports:
      - ${HOST_PORT}:80
    depends_on:
      - react
      - golang
